[project]
name = "psm-utils"
description = "Common utilities for parsing and handling peptide-spectrum matches and search engine results."
readme = "README.rst"
license = "Apache-2.0"
license-files = ["LICENSE"]
keywords = ["proteomics", "peptide", "spectrum", "identification", "parsing"]
authors = [
    { name = "Ralf Gabriels", email = "ralf@gabriels.dev" },
    { name = "Robbin Bouwmeester", email = "robbin.bouwmeester@ugent.be" },
    { name = "Arthur Declercq", email = "arthur.declercq@ugent.be" },
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Development Status :: 4 - Beta",
]
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "click",
    "lxml",
    "numpy",
    "pandas",
    "psims",
    "pyarrow",
    "pydantic >= 2",
    "pyteomics >= 4",
    "rich",
    "sqlalchemy >= 2",
]

[project.optional-dependencies]
dev = ["ruff", "isort>5", "pytest", "pytest-cov", "mypy"]
docs = [
    "numpydoc>=1,<2",
    "recommonmark",
    "semver>=2",
    "sphinx_rtd_theme",
    "sphinx-autobuild",
    "sphinx-mdinclude",
    "sphinx",
    "toml",
]
online = ["streamlit", "plotly"]
idxml = ["pyopenms"]
cbor = ["cbor2 >= 5"]
io = ["pyopenms", "cbor2 >= 5"]

[project.urls]
GitHub = "https://github.com/compomics/psm_utils"
ReadTheDocs = "https://psm-utils.readthedocs.io"
PyPi = "https://pypi.org/project/psm-utils/"
CompOmics = "https://www.compomics.com"

[project.scripts]
psm_utils = "psm_utils.__main__:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["psm_utils*"]

[tool.setuptools.dynamic]
version = { attr = "psm_utils.__version__" }

[tool.isort]
profile = "black"

[tool.black]
line-length = 99
target-version = ['py310']

[tool.ruff]
line-length = 99
target-version = "py310"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "PD", "D", "UP"]
ignore = ["D203", "D212"]

[tool.mypy]
files = ["psm_utils/**/*.py"]
install_types = true
