name: Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/psm-utils
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"

      - name: Build
        run: uv build

      - name: Test wheel
        run: uv run --isolated --with *.whl python -c "import psm_utils; print('Successfully imported built package.')"

      - name: Publish to PyPI
        run: uv publish
