name: Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/psm-utils
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest

      - name: Build
        run: python -m build --sdist --wheel .

      - name: Install wheel
        run: pip install dist/psm_utils-*.whl

      - name: Test wheel
        run: |
          pytest

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
